global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'polkadot-app'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['polkadot-railway-production.up.railway.app']
